import { useCallback } from "react";

import { ApiError } from "@/lib/api";
import { type Locale, useI18n } from "@/lib/i18n";

type ApiErrorCode =
  | "invalidCredentials"
  | "registrationDisabled"
  | "emailNotVerified"
  | "invalidToken"
  | "tokenExpired"
  | "resourceExists"
  | "passwordTooShort"
  | "usernameTooShort"
  | "usernameTooLong"
  | "usernameInvalidChars"
  | "invalidRequestBody"
  | "missingRefreshCookie"
  | "missingBearerToken"
  | "invalidAccessToken"
  | "missingAuthenticatedUser"
  | "adminAccessRequired"
  | "userNotFound"
  | "tenantNotFound"
  | "tenantDisabled"
  | "domainNotFound"
  | "endpointNotFound"
  | "domainAlreadyExists"
  | "hostnameRequired"
  | "targetIpInvalid"
  | "portOutOfRange"
  | "nameRequired"
  | "invalidEndpointConfig"
  | "telegramNotConfigured"
  | "frontendAssetsUnavailable"
  | "noSelectedUser"
  | "badRequest"
  | "unauthorized"
  | "forbidden"
  | "notFound"
  | "conflict"
  | "serverError";

const messageToCode: Record<string, ApiErrorCode> = {
  "invalid credentials": "invalidCredentials",
  "registration disabled": "registrationDisabled",
  "email not verified": "emailNotVerified",
  "invalid token": "invalidToken",
  "token expired": "tokenExpired",
  "resource already exists": "resourceExists",
  "password must be at least 8 characters": "passwordTooShort",
  "username must be at least 3 characters": "usernameTooShort",
  "username must be at most 32 characters": "usernameTooLong",
  "username may only contain letters, numbers, dot, underscore, and dash": "usernameInvalidChars",
  "invalid request body": "invalidRequestBody",
  "missing refresh cookie": "missingRefreshCookie",
  "missing bearer token": "missingBearerToken",
  "invalid access token": "invalidAccessToken",
  "missing authenticated user": "missingAuthenticatedUser",
  "admin access required": "adminAccessRequired",
  "user not found": "userNotFound",
  "tenant not found": "tenantNotFound",
  "tenant is disabled": "tenantDisabled",
  "domain not found": "domainNotFound",
  "endpoint not found": "endpointNotFound",
  "domain already exists": "domainAlreadyExists",
  "hostname is required": "hostnameRequired",
  "target ip must be a valid ipv4 or ipv6 address": "targetIpInvalid",
  "port must be between 1 and 65535": "portOutOfRange",
  "name is required": "nameRequired",
  "invalid endpoint config": "invalidEndpointConfig",
  "telegram bot token is not configured": "telegramNotConfigured",
  "frontend assets are not available": "frontendAssetsUnavailable",
  "no selected user": "noSelectedUser",
};

const localizedMessages: Record<Locale, Record<ApiErrorCode, string>> = {
  "zh-CN": {
    invalidCredentials: "用户名或密码错误。",
    registrationDisabled: "当前已关闭注册。",
    emailNotVerified: "邮箱尚未验证。",
    invalidToken: "令牌无效。",
    tokenExpired: "令牌已过期。",
    resourceExists: "资源已存在。",
    passwordTooShort: "密码至少需要 8 个字符。",
    usernameTooShort: "用户名至少需要 3 个字符。",
    usernameTooLong: "用户名最多允许 32 个字符。",
    usernameInvalidChars: "用户名只能包含字母、数字、点号、下划线和短横线。",
    invalidRequestBody: "请求内容无效。",
    missingRefreshCookie: "缺少刷新会话所需的 Cookie。",
    missingBearerToken: "缺少访问令牌。",
    invalidAccessToken: "访问令牌无效。",
    missingAuthenticatedUser: "当前登录状态无效，请重新登录。",
    adminAccessRequired: "需要管理员权限。",
    userNotFound: "未找到用户。",
    tenantNotFound: "未找到租户。",
    tenantDisabled: "该租户已被禁用。",
    domainNotFound: "未找到域名。",
    endpointNotFound: "未找到通知端点。",
    domainAlreadyExists: "该域名已存在。",
    hostnameRequired: "主机名不能为空。",
    targetIpInvalid: "指定 IP 必须是有效的 IPv4 或 IPv6 地址。",
    portOutOfRange: "端口必须在 1 到 65535 之间。",
    nameRequired: "名称不能为空。",
    invalidEndpointConfig: "通知端点配置无效。",
    telegramNotConfigured: "Telegram 机器人令牌尚未配置。",
    frontendAssetsUnavailable: "前端资源当前不可用。",
    noSelectedUser: "请先选择一个用户。",
    badRequest: "请求无效。",
    unauthorized: "当前操作未授权，请重新登录。",
    forbidden: "没有权限执行该操作。",
    notFound: "请求的资源不存在。",
    conflict: "资源冲突，请检查是否已存在。",
    serverError: "服务器处理请求时发生错误。",
  },
  "zh-TW": {
    invalidCredentials: "使用者名稱或密碼錯誤。",
    registrationDisabled: "目前已關閉註冊。",
    emailNotVerified: "電子郵件尚未驗證。",
    invalidToken: "權杖無效。",
    tokenExpired: "權杖已過期。",
    resourceExists: "資源已存在。",
    passwordTooShort: "密碼至少需要 8 個字元。",
    usernameTooShort: "使用者名稱至少需要 3 個字元。",
    usernameTooLong: "使用者名稱最多允許 32 個字元。",
    usernameInvalidChars: "使用者名稱只能包含字母、數字、點、底線與連字號。",
    invalidRequestBody: "請求內容無效。",
    missingRefreshCookie: "缺少重新整理會話所需的 Cookie。",
    missingBearerToken: "缺少存取權杖。",
    invalidAccessToken: "存取權杖無效。",
    missingAuthenticatedUser: "目前登入狀態無效，請重新登入。",
    adminAccessRequired: "需要管理員權限。",
    userNotFound: "找不到使用者。",
    tenantNotFound: "找不到租戶。",
    tenantDisabled: "此租戶已被停用。",
    domainNotFound: "找不到網域。",
    endpointNotFound: "找不到通知端點。",
    domainAlreadyExists: "此網域已存在。",
    hostnameRequired: "主機名稱不能為空。",
    targetIpInvalid: "指定 IP 必須是有效的 IPv4 或 IPv6 位址。",
    portOutOfRange: "埠號必須介於 1 到 65535 之間。",
    nameRequired: "名稱不能為空。",
    invalidEndpointConfig: "通知端點設定無效。",
    telegramNotConfigured: "尚未設定 Telegram 機器人權杖。",
    frontendAssetsUnavailable: "前端資源目前無法使用。",
    noSelectedUser: "請先選擇一位使用者。",
    badRequest: "請求無效。",
    unauthorized: "目前操作未授權，請重新登入。",
    forbidden: "沒有權限執行此操作。",
    notFound: "找不到要求的資源。",
    conflict: "資源衝突，請確認是否已存在。",
    serverError: "伺服器處理請求時發生錯誤。",
  },
  en: {
    invalidCredentials: "Incorrect username or password.",
    registrationDisabled: "Registration is currently disabled.",
    emailNotVerified: "Email verification is still pending.",
    invalidToken: "The token is invalid.",
    tokenExpired: "The token has expired.",
    resourceExists: "The resource already exists.",
    passwordTooShort: "Password must be at least 8 characters.",
    usernameTooShort: "Username must be at least 3 characters.",
    usernameTooLong: "Username must be at most 32 characters.",
    usernameInvalidChars: "Username may only contain letters, numbers, dots, underscores, and dashes.",
    invalidRequestBody: "The request body is invalid.",
    missingRefreshCookie: "The refresh cookie is missing.",
    missingBearerToken: "The access token is missing.",
    invalidAccessToken: "The access token is invalid.",
    missingAuthenticatedUser: "Your session is no longer valid. Please sign in again.",
    adminAccessRequired: "Admin access is required.",
    userNotFound: "The user could not be found.",
    tenantNotFound: "The tenant could not be found.",
    tenantDisabled: "This tenant has been disabled.",
    domainNotFound: "The domain could not be found.",
    endpointNotFound: "The notification endpoint could not be found.",
    domainAlreadyExists: "This domain already exists.",
    hostnameRequired: "Hostname is required.",
    targetIpInvalid: "Pinned IP must be a valid IPv4 or IPv6 address.",
    portOutOfRange: "Port must be between 1 and 65535.",
    nameRequired: "Name is required.",
    invalidEndpointConfig: "The notification endpoint configuration is invalid.",
    telegramNotConfigured: "Telegram bot token is not configured.",
    frontendAssetsUnavailable: "Frontend assets are not available.",
    noSelectedUser: "Select a user first.",
    badRequest: "The request is invalid.",
    unauthorized: "You are not authorized for this action.",
    forbidden: "You do not have permission for this action.",
    notFound: "The requested resource could not be found.",
    conflict: "The request conflicts with an existing resource.",
    serverError: "The server failed to process the request.",
  },
  es: {
    invalidCredentials: "Nombre de usuario o contraseña incorrectos.",
    registrationDisabled: "El registro está deshabilitado actualmente.",
    emailNotVerified: "El correo electrónico aún no está verificado.",
    invalidToken: "El token no es válido.",
    tokenExpired: "El token ha expirado.",
    resourceExists: "El recurso ya existe.",
    passwordTooShort: "La contraseña debe tener al menos 8 caracteres.",
    usernameTooShort: "El nombre de usuario debe tener al menos 3 caracteres.",
    usernameTooLong: "El nombre de usuario debe tener como máximo 32 caracteres.",
    usernameInvalidChars: "El nombre de usuario solo puede contener letras, números, puntos, guiones bajos y guiones.",
    invalidRequestBody: "El contenido de la solicitud no es válido.",
    missingRefreshCookie: "Falta la cookie de actualización de sesión.",
    missingBearerToken: "Falta el token de acceso.",
    invalidAccessToken: "El token de acceso no es válido.",
    missingAuthenticatedUser: "La sesión ya no es válida. Inicia sesión de nuevo.",
    adminAccessRequired: "Se requiere acceso de administrador.",
    userNotFound: "No se encontró el usuario.",
    tenantNotFound: "No se encontró el tenant.",
    tenantDisabled: "Este tenant está deshabilitado.",
    domainNotFound: "No se encontró el dominio.",
    endpointNotFound: "No se encontró el endpoint de notificación.",
    domainAlreadyExists: "Este dominio ya existe.",
    hostnameRequired: "El hostname es obligatorio.",
    targetIpInvalid: "La IP fijada debe ser una dirección IPv4 o IPv6 válida.",
    portOutOfRange: "El puerto debe estar entre 1 y 65535.",
    nameRequired: "El nombre es obligatorio.",
    invalidEndpointConfig: "La configuración del endpoint de notificación no es válida.",
    telegramNotConfigured: "El token del bot de Telegram no está configurado.",
    frontendAssetsUnavailable: "Los recursos del frontend no están disponibles.",
    noSelectedUser: "Selecciona primero un usuario.",
    badRequest: "La solicitud no es válida.",
    unauthorized: "No estás autorizado para esta acción.",
    forbidden: "No tienes permiso para realizar esta acción.",
    notFound: "No se encontró el recurso solicitado.",
    conflict: "La solicitud entra en conflicto con un recurso existente.",
    serverError: "El servidor no pudo procesar la solicitud.",
  },
  fr: {
    invalidCredentials: "Nom d'utilisateur ou mot de passe incorrect.",
    registrationDisabled: "L'inscription est actuellement désactivée.",
    emailNotVerified: "L'adresse e-mail n'est pas encore vérifiée.",
    invalidToken: "Le jeton est invalide.",
    tokenExpired: "Le jeton a expiré.",
    resourceExists: "La ressource existe déjà.",
    passwordTooShort: "Le mot de passe doit contenir au moins 8 caractères.",
    usernameTooShort: "Le nom d'utilisateur doit contenir au moins 3 caractères.",
    usernameTooLong: "Le nom d'utilisateur doit contenir au plus 32 caractères.",
    usernameInvalidChars: "Le nom d'utilisateur ne peut contenir que des lettres, chiffres, points, tirets bas et tirets.",
    invalidRequestBody: "Le contenu de la requête est invalide.",
    missingRefreshCookie: "Le cookie de rafraîchissement est manquant.",
    missingBearerToken: "Le jeton d'accès est manquant.",
    invalidAccessToken: "Le jeton d'accès est invalide.",
    missingAuthenticatedUser: "Votre session n'est plus valide. Veuillez vous reconnecter.",
    adminAccessRequired: "Un accès administrateur est requis.",
    userNotFound: "Utilisateur introuvable.",
    tenantNotFound: "Locataire introuvable.",
    tenantDisabled: "Ce locataire a été désactivé.",
    domainNotFound: "Domaine introuvable.",
    endpointNotFound: "Point de notification introuvable.",
    domainAlreadyExists: "Ce domaine existe déjà.",
    hostnameRequired: "Le nom d'hôte est requis.",
    targetIpInvalid: "L’IP cible doit être une adresse IPv4 ou IPv6 valide.",
    portOutOfRange: "Le port doit être compris entre 1 et 65535.",
    nameRequired: "Le nom est requis.",
    invalidEndpointConfig: "La configuration du point de notification est invalide.",
    telegramNotConfigured: "Le jeton du bot Telegram n'est pas configuré.",
    frontendAssetsUnavailable: "Les ressources front-end ne sont pas disponibles.",
    noSelectedUser: "Sélectionnez d'abord un utilisateur.",
    badRequest: "La requête est invalide.",
    unauthorized: "Vous n'êtes pas autorisé à effectuer cette action.",
    forbidden: "Vous n'avez pas l'autorisation d'effectuer cette action.",
    notFound: "La ressource demandée est introuvable.",
    conflict: "La requête entre en conflit avec une ressource existante.",
    serverError: "Le serveur n'a pas pu traiter la requête.",
  },
  de: {
    invalidCredentials: "Falscher Benutzername oder Passwort.",
    registrationDisabled: "Die Registrierung ist derzeit deaktiviert.",
    emailNotVerified: "Die Verifizierung von Email steht noch aus.",
    invalidToken: "Der Token ist ungültig.",
    tokenExpired: "Der Token ist abgelaufen.",
    resourceExists: "Die Ressource existiert bereits.",
    passwordTooShort: "Das Passwort muss mindestens 8 Zeichen lang sein.",
    usernameTooShort: "Der Benutzername muss mindestens 3 Zeichen lang sein.",
    usernameTooLong: "Der Benutzername darf höchstens 32 Zeichen lang sein.",
    usernameInvalidChars: "Der Benutzername darf nur Buchstaben, Zahlen, Punkte, Unterstriche und Bindestriche enthalten.",
    invalidRequestBody: "Der Anfragetext ist ungültig.",
    missingRefreshCookie: "Das Aktualisierungscookie fehlt.",
    missingBearerToken: "Das Zugriffstoken fehlt.",
    invalidAccessToken: "Das Zugriffstoken ist ungültig.",
    missingAuthenticatedUser: "Ihre Sitzung ist nicht mehr gültig. Bitte melden Sie sich erneut an.",
    adminAccessRequired: "Administratorzugriff ist erforderlich.",
    userNotFound: "Der Benutzer konnte nicht gefunden werden.",
    tenantNotFound: "Der Mieter konnte nicht gefunden werden.",
    tenantDisabled: "Dieser Mieter wurde deaktiviert.",
    domainNotFound: "Die Domain konnte nicht gefunden werden.",
    endpointNotFound: "Der Benachrichtigungsendpunkt konnte nicht gefunden werden.",
    domainAlreadyExists: "Diese Domain existiert bereits.",
    hostnameRequired: "Hostname ist erforderlich.",
    targetIpInvalid: "Die angeheftete IP muss eine gültige IPv4- oder IPv6-Adresse sein.",
    portOutOfRange: "Der Port muss zwischen 1 und 65535 liegen.",
    nameRequired: "Name ist erforderlich.",
    invalidEndpointConfig: "Die Konfiguration des Benachrichtigungsendpunkts ist ungültig.",
    telegramNotConfigured: "Telegram Bot-Token ist nicht konfiguriert.",
    frontendAssetsUnavailable: "Frontend Assets sind nicht verfügbar.",
    noSelectedUser: "Wählen Sie zunächst einen Benutzer aus.",
    badRequest: "Die Anfrage ist ungültig.",
    unauthorized: "Sie sind für diese Aktion nicht berechtigt.",
    forbidden: "Sie haben keine Berechtigung für diese Aktion.",
    notFound: "Die angeforderte Ressource konnte nicht gefunden werden.",
    conflict: "Die Anfrage steht in Konflikt mit einer vorhandenen Ressource.",
    serverError: "Der Server konnte die Anfrage nicht verarbeiten.",
  },
  ru: {
    invalidCredentials: "Неверное имя пользователя или пароль.",
    registrationDisabled: "Регистрация сейчас отключена.",
    emailNotVerified: "Электронная почта ещё не подтверждена.",
    invalidToken: "Токен недействителен.",
    tokenExpired: "Срок действия токена истёк.",
    resourceExists: "Ресурс уже существует.",
    passwordTooShort: "Пароль должен содержать не менее 8 символов.",
    usernameTooShort: "Имя пользователя должно содержать не менее 3 символов.",
    usernameTooLong: "Имя пользователя должно содержать не более 32 символов.",
    usernameInvalidChars: "Имя пользователя может содержать только буквы, цифры, точки, подчёркивания и дефисы.",
    invalidRequestBody: "Содержимое запроса недействительно.",
    missingRefreshCookie: "Отсутствует cookie для обновления сессии.",
    missingBearerToken: "Отсутствует токен доступа.",
    invalidAccessToken: "Токен доступа недействителен.",
    missingAuthenticatedUser: "Сеанс больше недействителен. Войдите снова.",
    adminAccessRequired: "Требуются права администратора.",
    userNotFound: "Пользователь не найден.",
    tenantNotFound: "Арендатор не найден.",
    tenantDisabled: "Этот арендатор отключён.",
    domainNotFound: "Домен не найден.",
    endpointNotFound: "Точка уведомлений не найдена.",
    domainAlreadyExists: "Этот домен уже существует.",
    hostnameRequired: "Имя хоста обязательно.",
    targetIpInvalid: "Заданный IP должен быть корректным адресом IPv4 или IPv6.",
    portOutOfRange: "Порт должен быть в диапазоне от 1 до 65535.",
    nameRequired: "Имя обязательно.",
    invalidEndpointConfig: "Конфигурация точки уведомлений недействительна.",
    telegramNotConfigured: "Токен Telegram-бота не настроен.",
    frontendAssetsUnavailable: "Фронтенд-ресурсы недоступны.",
    noSelectedUser: "Сначала выберите пользователя.",
    badRequest: "Некорректный запрос.",
    unauthorized: "У вас нет авторизации для этого действия.",
    forbidden: "У вас нет прав для этого действия.",
    notFound: "Запрошенный ресурс не найден.",
    conflict: "Запрос конфликтует с уже существующим ресурсом.",
    serverError: "Сервер не смог обработать запрос.",
  },
  ar: {
    invalidCredentials: "اسم المستخدم أو كلمة المرور غير صحيحة.",
    registrationDisabled: "التسجيل معطل حاليا.",
    emailNotVerified: "Email لا يزال التحقق معلقًا.",
    invalidToken: "الرمز غير صالح.",
    tokenExpired: "انتهت صلاحية الرمز المميز.",
    resourceExists: "المورد موجود بالفعل.",
    passwordTooShort: "يجب أن تتكون كلمة المرور من 8 أحرف على الأقل.",
    usernameTooShort: "يجب أن يكون اسم المستخدم 3 أحرف على الأقل.",
    usernameTooLong: "يجب أن يكون اسم المستخدم 32 حرفًا على الأكثر.",
    usernameInvalidChars: "يجب أن يحتوي اسم المستخدم فقط على أحرف وأرقام ونقاط وشرطات سفلية وشرطات.",
    invalidRequestBody: "نص الطلب غير صالح.",
    missingRefreshCookie: "ملف تعريف الارتباط التحديث مفقود.",
    missingBearerToken: "رمز الوصول مفقود.",
    invalidAccessToken: "رمز الوصول غير صالح.",
    missingAuthenticatedUser: "جلستك لم تعد صالحة. الرجاء تسجيل الدخول مرة أخرى.",
    adminAccessRequired: "مطلوب وصول المشرف.",
    userNotFound: "لا يمكن العثور على المستخدم.",
    tenantNotFound: "لا يمكن العثور على المستأجر.",
    tenantDisabled: "لقد تم تعطيل هذا المستأجر.",
    domainNotFound: "لا يمكن العثور على المجال.",
    endpointNotFound: "تعذر العثور على نقطة نهاية الإشعار.",
    domainAlreadyExists: "هذا المجال موجود بالفعل.",
    hostnameRequired: "اسم المضيف مطلوب.",
    targetIpInvalid: "يجب أن يكون عنوان IP المثبت عنوان IPv4 أو IPv6 صالحًا.",
    portOutOfRange: "يجب أن يكون المنفذ بين 1 و65535.",
    nameRequired: "الاسم مطلوب.",
    invalidEndpointConfig: "تكوين نقطة نهاية الإعلام غير صالح.",
    telegramNotConfigured: "Telegram لم يتم تكوين رمز الروبوت المميز.",
    frontendAssetsUnavailable: "Frontend الأصول غير متوفرة.",
    noSelectedUser: "حدد مستخدمًا أولاً.",
    badRequest: "الطلب غير صالح.",
    unauthorized: "أنت غير مصرح لك بهذا الإجراء.",
    forbidden: "ليس لديك إذن بهذا الإجراء.",
    notFound: "لا يمكن العثور على المورد المطلوب.",
    conflict: "يتعارض الطلب مع مورد موجود.",
    serverError: "فشل الخادم في معالجة الطلب.",
  },
  pt: {
    invalidCredentials: "Nome de usuário ou senha incorretos.",
    registrationDisabled: "O registro está desativado no momento.",
    emailNotVerified: "A verificação de Email ainda está pendente.",
    invalidToken: "O token é inválido.",
    tokenExpired: "O token expirou.",
    resourceExists: "O recurso já existe.",
    passwordTooShort: "A senha deve ter pelo menos 8 caracteres.",
    usernameTooShort: "O nome de usuário deve ter pelo menos 3 caracteres.",
    usernameTooLong: "O nome de usuário deve ter no máximo 32 caracteres.",
    usernameInvalidChars: "O nome de usuário pode conter apenas letras, números, pontos, sublinhados e travessões.",
    invalidRequestBody: "O corpo da solicitação é inválido.",
    missingRefreshCookie: "O cookie de atualização está faltando.",
    missingBearerToken: "O token de acesso está faltando.",
    invalidAccessToken: "O token de acesso é inválido.",
    missingAuthenticatedUser: "Sua sessão não é mais válida. Faça login novamente.",
    adminAccessRequired: "É necessário acesso de administrador.",
    userNotFound: "O usuário não foi encontrado.",
    tenantNotFound: "O inquilino não foi encontrado.",
    tenantDisabled: "Este inquilino foi desativado.",
    domainNotFound: "O domínio não foi encontrado.",
    endpointNotFound: "O endpoint de notificação não pôde ser encontrado.",
    domainAlreadyExists: "Este domínio já existe.",
    hostnameRequired: "O nome do host é obrigatório.",
    targetIpInvalid: "O IP fixado deve ser um endereço IPv4 ou IPv6 válido.",
    portOutOfRange: "A porta deve estar entre 1 e 65535.",
    nameRequired: "O nome é obrigatório.",
    invalidEndpointConfig: "A configuração do terminal de notificação é inválida.",
    telegramNotConfigured: "O token do bot Telegram não está configurado.",
    frontendAssetsUnavailable: "Frontend ativos não estão disponíveis.",
    noSelectedUser: "Selecione um usuário primeiro.",
    badRequest: "A solicitação é inválida.",
    unauthorized: "Você não está autorizado para esta ação.",
    forbidden: "Você não tem permissão para esta ação.",
    notFound: "O recurso solicitado não foi encontrado.",
    conflict: "A solicitação entra em conflito com um recurso existente.",
    serverError: "O servidor não conseguiu processar a solicitação.",
  },
  ja: {
    invalidCredentials: "ユーザー名またはパスワードが正しくありません。",
    registrationDisabled: "現在、登録は無効になっています。",
    emailNotVerified: "メールアドレスの確認がまだ完了していません。",
    invalidToken: "トークンが無効です。",
    tokenExpired: "トークンの有効期限が切れています。",
    resourceExists: "リソースはすでに存在します。",
    passwordTooShort: "パスワードは 8 文字以上である必要があります。",
    usernameTooShort: "ユーザー名は 3 文字以上である必要があります。",
    usernameTooLong: "ユーザー名は 32 文字以下である必要があります。",
    usernameInvalidChars: "ユーザー名には英字、数字、ドット、アンダースコア、ハイフンのみ使用できます。",
    invalidRequestBody: "リクエスト内容が不正です。",
    missingRefreshCookie: "セッション更新用の Cookie がありません。",
    missingBearerToken: "アクセストークンがありません。",
    invalidAccessToken: "アクセストークンが無効です。",
    missingAuthenticatedUser: "セッションが無効です。もう一度ログインしてください。",
    adminAccessRequired: "管理者権限が必要です。",
    userNotFound: "ユーザーが見つかりません。",
    tenantNotFound: "テナントが見つかりません。",
    tenantDisabled: "このテナントは無効化されています。",
    domainNotFound: "ドメインが見つかりません。",
    endpointNotFound: "通知エンドポイントが見つかりません。",
    domainAlreadyExists: "このドメインはすでに存在します。",
    hostnameRequired: "ホスト名は必須です。",
    targetIpInvalid: "指定 IP は有効な IPv4 または IPv6 アドレスである必要があります。",
    portOutOfRange: "ポートは 1 から 65535 の範囲で指定してください。",
    nameRequired: "名前は必須です。",
    invalidEndpointConfig: "通知エンドポイントの設定が不正です。",
    telegramNotConfigured: "Telegram ボットトークンが設定されていません。",
    frontendAssetsUnavailable: "フロントエンドのアセットが利用できません。",
    noSelectedUser: "先にユーザーを選択してください。",
    badRequest: "リクエストが不正です。",
    unauthorized: "この操作を行う権限がありません。",
    forbidden: "この操作を実行する権限がありません。",
    notFound: "要求されたリソースが見つかりません。",
    conflict: "既存のリソースと競合しています。",
    serverError: "サーバーがリクエストを処理できませんでした。",
  },
  ko: {
    invalidCredentials: "사용자 이름이나 비밀번호가 잘못되었습니다.",
    registrationDisabled: "현재 등록이 비활성화되어 있습니다.",
    emailNotVerified: "Email 확인이 아직 보류 중입니다.",
    invalidToken: "토큰이 유효하지 않습니다.",
    tokenExpired: "토큰이 만료되었습니다.",
    resourceExists: "리소스가 이미 존재합니다.",
    passwordTooShort: "비밀번호는 8자 이상이어야 합니다.",
    usernameTooShort: "사용자 이름은 3자 이상이어야 합니다.",
    usernameTooLong: "사용자 이름은 최대 32자여야 합니다.",
    usernameInvalidChars: "사용자 이름에는 문자, 숫자, 점, 밑줄, 대시만 포함할 수 있습니다.",
    invalidRequestBody: "요청 본문이 잘못되었습니다.",
    missingRefreshCookie: "새로 고침 쿠키가 없습니다.",
    missingBearerToken: "액세스 토큰이 누락되었습니다.",
    invalidAccessToken: "액세스 토큰이 잘못되었습니다.",
    missingAuthenticatedUser: "귀하의 세션은 더 이상 유효하지 않습니다. 다시 로그인해 주세요.",
    adminAccessRequired: "관리자 액세스가 필요합니다.",
    userNotFound: "사용자를 찾을 수 없습니다.",
    tenantNotFound: "임차인을 찾을 수 없습니다.",
    tenantDisabled: "이 테넌트는 비활성화되었습니다.",
    domainNotFound: "도메인을 찾을 수 없습니다.",
    endpointNotFound: "알림 엔드포인트를 찾을 수 없습니다.",
    domainAlreadyExists: "이 도메인은 이미 존재합니다.",
    hostnameRequired: "호스트 이름이 필요합니다.",
    targetIpInvalid: "고정된 IP는 유효한 IPv4 또는 IPv6 주소여야 합니다.",
    portOutOfRange: "포트는 1에서 65535 사이여야 합니다.",
    nameRequired: "이름은 필수입니다.",
    invalidEndpointConfig: "알림 끝점 구성이 잘못되었습니다.",
    telegramNotConfigured: "Telegram 봇 토큰이 구성되지 않았습니다.",
    frontendAssetsUnavailable: "Frontend 자산을 사용할 수 없습니다.",
    noSelectedUser: "먼저 사용자를 선택하세요.",
    badRequest: "요청이 잘못되었습니다.",
    unauthorized: "이 작업을 수행할 권한이 없습니다.",
    forbidden: "이 작업에 대한 권한이 없습니다.",
    notFound: "요청한 리소스를 찾을 수 없습니다.",
    conflict: "요청이 기존 리소스와 충돌합니다.",
    serverError: "서버가 요청을 처리하지 못했습니다.",
  },
  hi: {
    invalidCredentials: "गलत उपयोगकर्ता नाम या पासवर्ड।",
    registrationDisabled: "पंजीकरण फिलहाल अक्षम है.",
    emailNotVerified: "Email सत्यापन अभी भी लंबित है.",
    invalidToken: "टोकन अमान्य है.",
    tokenExpired: "टोकन समाप्त हो गया है.",
    resourceExists: "संसाधन पहले से मौजूद है.",
    passwordTooShort: "पासवर्ड कम से कम 8 वर्णों का होना चाहिए।",
    usernameTooShort: "उपयोगकर्ता नाम कम से कम 3 अक्षर का होना चाहिए.",
    usernameTooLong: "उपयोगकर्ता नाम अधिकतम 32 अक्षर का होना चाहिए.",
    usernameInvalidChars: "उपयोगकर्ता नाम में केवल अक्षर, संख्याएँ, बिंदु, अंडरस्कोर और डैश हो सकते हैं।",
    invalidRequestBody: "अनुरोध का मुख्य भाग अमान्य है.",
    missingRefreshCookie: "ताज़ा कुकी गायब है.",
    missingBearerToken: "एक्सेस टोकन गायब है.",
    invalidAccessToken: "एक्सेस टोकन अमान्य है.",
    missingAuthenticatedUser: "अपका सत्र अब मान्य नहीं है। कृपया पुनः साइन इन करें.",
    adminAccessRequired: "व्यवस्थापक पहुंच आवश्यक है.",
    userNotFound: "उपयोगकर्ता नहीं मिल सका.",
    tenantNotFound: "किरायेदार नहीं मिल सका.",
    tenantDisabled: "इस किरायेदार को अक्षम कर दिया गया है.",
    domainNotFound: "डोमेन नहीं मिल सका.",
    endpointNotFound: "अधिसूचना समापन बिंदु नहीं पाया जा सका.",
    domainAlreadyExists: "यह डोमेन पहले से मौजूद है.",
    hostnameRequired: "होस्टनाम आवश्यक है.",
    targetIpInvalid: "पिन किया गया IP एक वैध IPv4 या IPv6 पता होना चाहिए।",
    portOutOfRange: "पोर्ट 1 और 65535 के बीच होना चाहिए।",
    nameRequired: "नाम आवश्यक है।",
    invalidEndpointConfig: "अधिसूचना समापन बिंदु कॉन्फ़िगरेशन अमान्य है.",
    telegramNotConfigured: "Telegram बॉट टोकन कॉन्फ़िगर नहीं किया गया है।",
    frontendAssetsUnavailable: "Frontend संपत्तियां उपलब्ध नहीं हैं.",
    noSelectedUser: "पहले एक उपयोगकर्ता चुनें.",
    badRequest: "अनुरोध अमान्य है.",
    unauthorized: "आप इस कार्रवाई के लिए अधिकृत नहीं हैं.",
    forbidden: "आपके पास इस कार्रवाई की अनुमति नहीं है.",
    notFound: "अनुरोधित संसाधन नहीं मिल सका.",
    conflict: "अनुरोध मौजूदा संसाधन के साथ टकराव करता है।",
    serverError: "सर्वर अनुरोध संसाधित करने में विफल रहा.",
  },
  it: {
    invalidCredentials: "Nome utente o password errati.",
    registrationDisabled: "La registrazione è attualmente disabilitata.",
    emailNotVerified: "La verifica Email è ancora in sospeso.",
    invalidToken: "Il token non è valido.",
    tokenExpired: "Il token è scaduto.",
    resourceExists: "La risorsa esiste già.",
    passwordTooShort: "La password deve contenere almeno 8 caratteri.",
    usernameTooShort: "Il nome utente deve contenere almeno 3 caratteri.",
    usernameTooLong: "Il nome utente deve contenere al massimo 32 caratteri.",
    usernameInvalidChars: "Il nome utente può contenere solo lettere, numeri, punti, trattini bassi e trattini.",
    invalidRequestBody: "Il corpo della richiesta non è valido.",
    missingRefreshCookie: "Manca il cookie di aggiornamento.",
    missingBearerToken: "Manca il token di accesso.",
    invalidAccessToken: "Il token di accesso non è valido.",
    missingAuthenticatedUser: "La tua sessione non è più valida. Per favore accedi di nuovo.",
    adminAccessRequired: "È richiesto l'accesso amministrativo.",
    userNotFound: "Impossibile trovare l'utente.",
    tenantNotFound: "Non è stato possibile trovare l'inquilino.",
    tenantDisabled: "Questo inquilino è stato disabilitato.",
    domainNotFound: "Impossibile trovare il dominio.",
    endpointNotFound: "Impossibile trovare l'endpoint di notifica.",
    domainAlreadyExists: "Questo dominio esiste già.",
    hostnameRequired: "Il nome host è obbligatorio.",
    targetIpInvalid: "L'IP bloccato deve essere un indirizzo IPv4 o IPv6 valido.",
    portOutOfRange: "La porta deve essere compresa tra 1 e 65535.",
    nameRequired: "Il nome è obbligatorio.",
    invalidEndpointConfig: "La configurazione dell'endpoint di notifica non è valida.",
    telegramNotConfigured: "Il token bot Telegram non è configurato.",
    frontendAssetsUnavailable: "Le risorse Frontend non sono disponibili.",
    noSelectedUser: "Seleziona prima un utente.",
    badRequest: "La richiesta non è valida.",
    unauthorized: "Non sei autorizzato per questa azione.",
    forbidden: "Non hai l'autorizzazione per questa azione.",
    notFound: "Impossibile trovare la risorsa richiesta.",
    conflict: "La richiesta è in conflitto con una risorsa esistente.",
    serverError: "Il server non è riuscito a elaborare la richiesta.",
  },
};

function normalizeMessage(message: string) {
  return message.trim().toLowerCase();
}

function codeFromStatus(status: number): ApiErrorCode | null {
  if (status >= 500) return "serverError";
  if (status === 409) return "conflict";
  if (status === 404) return "notFound";
  if (status === 403) return "forbidden";
  if (status === 401) return "unauthorized";
  if (status === 400) return "badRequest";
  return null;
}

function codeFromReason(reason: unknown): ApiErrorCode | null {
  if (!(reason instanceof Error)) {
    return null;
  }

  const normalized = normalizeMessage(reason.message);
  const messageCode = messageToCode[normalized];
  if (messageCode) {
    return messageCode;
  }

  if (reason instanceof ApiError) {
    return codeFromStatus(reason.status);
  }

  return null;
}

export function getLocalizedApiErrorMessage(locale: Locale, reason: unknown, fallbackMessage: string) {
  const code = codeFromReason(reason);
  if (!code) {
    return fallbackMessage;
  }
  return localizedMessages[locale][code] ?? localizedMessages.en[code] ?? fallbackMessage;
}

export function useApiErrorMessage() {
  const { locale } = useI18n();

  return useCallback((reason: unknown, fallbackMessage: string) => {
    return getLocalizedApiErrorMessage(locale, reason, fallbackMessage);
  }, [locale]);
}
